schedules:
  commit:
    # Run short and medium suites on commit, on DDAC only.
    schedule: per_commit
    matrix:
      exclude:
        - java: ['openjdk11']
        - cassandra: ['dse-6.8', 'dse-6.7', 'dse-6.0', 'dse-5.1', 'dse-5.0', 'dse-4.8', 'dse-4.7', 'dse-4.6', '3.11', '3.0', '2.2', '2.1', '2.0', '1.2']
    env_vars: |
      TEST_GROUPS="short,medium"
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (1.1, 1.x, 1.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUPS="short,medium,long"
  adhoc:
    # Run full suite on demand.
    schedule: adhoc
    matrix:
      exclude:
        - java: ['openjdk11']
    env_vars: |
      TEST_GROUPS="short,medium,long"
java:
  - openjdk8
  - openjdk11
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - 3.11
  - 3.0
  - 2.2
  - 2.1
  - 2.0
  - 1.2
  - ddac-5.1
  - dse-4.6
  - dse-4.7
  - dse-4.8
  - dse-5.0
  - dse-5.1
  - dse-6.0
  - dse-6.7
  - dse-6.8
build:
  - type: maven
    version: 3.2.5
    goals: verify -P$TEST_GROUPS --fail-never -B
    properties: |
      com.datastax.dsbulk.commons.tests.ccm.CCM_VERSION=$CCM_VERSION
      com.datastax.dsbulk.commons.tests.ccm.CCM_IS_DDAC=$CCM_IS_DDAC
      com.datastax.dsbulk.commons.tests.ccm.CCM_IS_DSE=$CCM_IS_DSE
      com.datastax.dsbulk.commons.tests.ccm.JAVA_HOME=$CCM_JAVA_HOME
      com.datastax.dsbulk.commons.tests.ccm.PATH=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      max.simulacron.clusters=2
      max.ccm.clusters=1
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco:
    exec_pattern: "**/target/**.exec"
    exclusion_pattern: "com/datastax/dsbulk/**/generated/**/*"
