schedules:
  commit:
    # Run short and medium suites on commit, on DDAC only.
    schedule: per_commit
    matrix:
      exclude:
        - cassandra: ['dse-6.8', 'dse-6.7', 'dse-6.0', 'dse-5.1', 'dse-5.0', '3.11']
    env_vars: |
      TEST_GROUPS="short,medium"
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (1.1, 1.x, 1.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUPS="short,medium,long"
  adhoc:
    # Run short and medium suites on demand, on 3 different clusters (DSE, DDAC, OSS).
    schedule: adhoc
    matrix:
      exclude:
        - cassandra: ['dse-6.7', 'dse-5.1', 'dse-5.0']
        # - java: ['oraclejdk10']
    env_vars: |
      TEST_GROUPS="short,medium"
java:
  - openjdk8
  - openjdk11
  # Temporarily disable builds against JDK 10, see DAT-318
  # - oraclejdk10
os:
  - ubuntu/bionic64/java-driver
cassandra:
  # Temporarily disable builds with DSE 4.8, see DAT-312
  # - dse-4.8
  - dse-5.0
  - dse-5.1
  - dse-6.0
  - dse-6.7
  - dse-6.8
  - ddac-5.1
  - 3.11
build:
  - type: maven
    version: 3.2.5
    goals: verify -P$TEST_GROUPS --fail-never -B
    properties: |
      com.datastax.dsbulk.commons.tests.ccm.CCM_VERSION=$CCM_VERSION
      com.datastax.dsbulk.commons.tests.ccm.CCM_IS_DDAC=$CCM_IS_DDAC
      com.datastax.dsbulk.commons.tests.ccm.CCM_IS_DSE=$CCM_IS_DSE
      com.datastax.dsbulk.commons.tests.ccm.JAVA_HOME=$CCM_JAVA_HOME
      com.datastax.dsbulk.commons.tests.ccm.PATH=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      max.simulacron.clusters=2
      max.ccm.clusters=1
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco:
    exec_pattern: "**/target/**.exec"
    exclusion_pattern: "com/datastax/dsbulk/commons/cql3/Cql*,com/datastax/dsbulk/engine/schema/generated/Mapping*"
